### ISSUE TITLE
Avoid using magic numbers

### ISSUE THREAD

**Issue by bangerth** [juleoc02/SAND#17]
You have this piece of code:
```
        //calculate elasticity constraint merit
        {
            //First need to find biggest multiplier y - I then add 1 because it starts at 0 for no real good reason. I don't like this bit...
            double multiplier;
            if (2 * nonlinear_solution.block(3).linfty_norm() > 10)
            {
                multiplier = 2 * nonlinear_solution.block(3).linfty_norm();
            }
            else
            {
                multiplier = 10;
            }
            elasticity_constraint_merit = multiplier * test_rhs.block(3).l1_norm();
        }
```
This looks shady (and you mention this in a comment :-) ) because it's unclear to me what physical units the multiplier should have. Presumably, `nonlinear_solution.block(3)` will have physical units, and so then the bare number `10` should have the same physical units. But if you change units for `nonlinear_solution.block(3)` (e.g., by going from meters to kilometers, which imply that the entries of `nonlinear_solution.block(3)` are all divided by a factor of 1000, the `10` stays the same. This doesn't look right.

I think what I'm trying to say is that you're using a "magic number" 10 here, but why that is the right choice is something I don't understand.

**Comment by bangerth** [comment]
A few lines below you also have this:
```
            //First need to find biggest multiplier y - This uses the fraction to boundary and actually should work pretty well.
            double minimum_slack = 1;
            for (unsigned int k = 0; k < nonlinear_solution.block(5).size(); k++)
            {
                if (nonlinear_solution.block(5)[k] < minimum_slack)
                {
                    minimum_slack = nonlinear_solution.block(5)[k];
                }
            }
```
The question is whether `1` is a useful starting point. Do you assume that the actual minimum is always smaller than one so that the initializer doesn't matter? If so, start with
```
            double minimum_slack = std::numeric_limits<double>::max();
```
to make clear that the starting initializer is always expected to be overwritten.

**Comment by juleoc02** [comment]
For the second one, 1 is a useful number, because it is the largest possible slack variable in the solution - because the density must be between 0 and 1 and these slacks are the distance from either 0 or 1, the maximum value is 1. That said, it should probably be explained better in there.  As per the first one... I have no idea how to try to find an upper bound for absolute value of the multipliers on the elasticity constraint. 10 seemed to work better than both 1 and 100 for a starting guess. But yeah, I need a better value there.

**Comment by bangerth** [comment]
A general strategy to make this at least more readable is to introduce names for these values -- just `const` variables so that it's clear what they stand for. It also makes it easier to think (and document!) what the physical units of variables should be.
