### ISSUE TITLE
Line search without a 'break' statement?

### ISSUE THREAD

**Issue by bangerth** [juleoc02/SAND#18]
You have this:
```
    template<int dim>
    std::vector<double>
    SANDTopOpt<dim>::calculate_max_step_size() const {

        const double fraction_to_boundary = .995;

        double step_size_s_low = 0;
        double step_size_z_low = 0;
        double step_size_s_high = 1;
        double step_size_z_high = 1;
        double step_size_s, step_size_z;

        for (unsigned int k = 0; k < 50; k++) {
            step_size_s = (step_size_s_low + step_size_s_high) / 2;
            step_size_z = (step_size_z_low + step_size_z_high) / 2;

            const BlockVector<double> nonlinear_solution_test_s =
                    (fraction_to_boundary * nonlinear_solution) + (step_size_s
                                                                   * linear_solution);

            const BlockVector<double> nonlinear_solution_test_z =
                    (fraction_to_boundary * nonlinear_solution) + (step_size_z
                                                                   * linear_solution);

            const bool accept_s = (nonlinear_solution_test_s.block(5).is_non_negative())
                                  && (nonlinear_solution_test_s.block(7).is_non_negative());
            const bool accept_z = (nonlinear_solution_test_z.block(6).is_non_negative())
                                  && (nonlinear_solution_test_z.block(8).is_non_negative());

            if (accept_s) {
                step_size_s_low = step_size_s;
            } else {
                step_size_s_high = step_size_s;
            }
            if (accept_z) {
                step_size_z_low = step_size_z;
            } else {
                step_size_z_high = step_size_z;
            }
        }
//        std::cout << step_size_s_low << "    " << step_size_z_low << std::endl;
        std::vector<double> max_step = {step_size_s_low, step_size_z_low};
        return max_step;
    }
```
This always runs the full 50 iterations in the loop. Is this really what you want? Isn't there a point where you've made the step sizes small enough so that `accept_s` and `accept_z` will be true and so then `step_size_*_low` will end up being `2^{-50}`?

**Comment by juleoc02** [comment]
This should just be a binary search, the low and high step sizes should be approaching some value between 0 and 1 - and hopefully closer to 1 than 0. It's a pretty low-cost operation, so I figured there wasn't much harm in finding this value close to machine error, so I let it go 50 times. I know it's another magic number, but I figure it's not slowing anything too terribly much? I have not tested that claim though


Justin O'Connor

juleoc@colostate.edu

(719) 331-7990

________________________________

**Comment by bangerth** [comment]
Ah, I see now what you're saying. Yes, it's probably not too expensive to do that. An alternative would have been to just compute the ratio of `(fraction_to_boundary * nonlinear_solution) / linear_solution` (I think that there is a function `ratio()` in the vector class that allows you to compute this element by element) from which you can determine the maximal step size by taking the largest or smallest element of these ratios.
