### ISSUE TITLE
Break SANDTopOpt<dim>::set_bcids() into two functions

### ISSUE THREAD

**Issue by bangerth** [juleoc02/SAND#3]
This function currently does two things:
* It puts stuff into the `boundary_values` object
* It sets `boundary_id`s on certain faces.
These are conceptually separate tasks. They should be done in separate loops and, preferably, separate functions. This means that you have to loop over the cells twice, but that's ok -- it doesn't cost very much.

**Comment by bangerth** [comment]
Specifically, setting boundary ids would belong into the function that creates the triangulation.

**Comment by juleoc02** [comment]
I get separating these into separate tasks - they are pretty (very) different things conceptually. I think boundary IDs have for some reason always been in my head as being more related to the dof_handler than the triangulation - though them being part of the triangulation makes sense thinking about it now. (And the triangulation being a part of the dof_handler, I'm gonna claim I wasn't entirely off here)
