### ISSUE TITLE
Rename density_penalty

### ISSUE THREAD

**Issue by bangerth** [juleoc02/SAND#6]
The variable name suggests that it's a penalty factor, but it's really an exponent. The name should reflect that.

**Comment by juleoc02** [comment]
In everything I've read, the exponent is actually called the penalization factor - I'm not opposed to renaming it to reflect that it works as an exponent though. I'm assuming most things called penalty factors work by multiplication (like the name suggests)?

**Comment by bangerth** [comment]
On 9/22/20 7:51 AM, juleoc02 wrote:
> In everything I've read, the exponent is actually called the penalization 
> factor - I'm not opposed to renaming it to reflect that it works as an 
> exponent though. I'm assuming most things called penalty factors work by 
> multiplication (like the name suggests)?

Ah, I see. If that's the commonly used name then stick with it. If you were 
using comments to document variables and functions (which you should! :-) ) 
then that would be the place to point out that the "factor" is actually used 
as an "exponent".
