### ISSUE TITLE
A better way to set up your block matrix and vectors

### ISSUE THREAD

**Issue by bangerth** [juleoc02/SAND#7]
You currently do this all by hand: Your DoFHandler only has one variable that corresponds to the displacement, and then you have to query the number of displacement DoFs by hand and use that for setting up individual block sizes. You handle the density vector completely on the side, outside a DoFHandler, even though it also represents "degrees of freedom" (DoFs), and that further complicates things because you can't, for example, just output everything in one go. Finally, I think you never actually store the Lagrange multiplier from one iteration to the next, and you're not outputting it either.

A much easier approach would be to let the DoFHandler store everything:
* The displacement vector as a dim-component `FE_Q`
* The Lagrange multiplier as the same
* The density as a piecewise constant finite element field (i.e., a `FE_DGQ<dim>(0)`)
If you have it all in one place (one DoFHandler), initializing matrix sizes can be done as in step-22, for example, and you will have an easier way assembling the whole linear system as well because you really just need to write down the one big bilinear form.

**Comment by bangerth** [comment]
This is going to be a bigger change, but I'd recommend doing it now while the program is still relatively simple.

**Comment by bangerth** [comment]
(I forgot in the list above that you also need Lagrange multipliers for upper/lower bounds. They should also just go into the same big DoFHandler.)

**Comment by juleoc02** [comment]
For the upper/lower bounds - right now I don't have lagrange multipliers for those, because I rely on the log barriers to keep those constraints satisfied. I've seen (like in nocedal/wright) people using lagrange multipliers, but then using log barriers on slack variables (19.4 in Nocedal/Wright), but when we talked about that briefly, it seemed like that was just an extra step? Like, why not just put log barriers on my actual constrained variables?

**Comment by juleoc02** [comment]
I also have a single lagrange multiplier for the total volume constraint - is there a way to put this into the DoF Handler?

**Comment by bangerth** [comment]
On 9/22/20 8:11 AM, juleoc02 wrote:
> For the upper/lower bounds - right now I don't have lagrange multipliers for 
> those, because I rely on the log barriers to keep those constraints satisfied. 
> I've seen (like in nocedal/wright) people using lagrange multipliers, but then 
> using log barriers on slack variables (19.4 in Nocedal/Wright), but when we 
> talked about that briefly, it seemed like that was just an extra step? Like, 
> why not just put log barriers on my actual constrained variables?

Right, I had just misremembered the approach you are currently using. Forget 
that part then.

**Comment by bangerth** [comment]
On 9/22/20 9:03 AM, juleoc02 wrote:
> I also have a single lagrange multiplier for the total volume constraint - is 
> there a way to put this into the DoF Handler?

Not easily. Though, since it's a linear constraint, you could add it to the 
AffineConstraints object.
